# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/node:12

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            - image: circleci/mongo:4.2.0

        working_directory: ~/repo

        steps:
            - checkout:

            - run: cd backend && yarn install
            # run tests!
            - run: cd backend && yarn test
            # run e2e tests
            - run: cd backend && yarn test:e2e
